#!/usr/bin/env bash
set -uo pipefail

# Claude Chroot IP Allowlist Sync Script
# Run this periodically to update the IP list for the chroot firewall

IP_FILE="/srv/claude-chroot/allowed-ips.conf"
FAILED_DOMAINS=()
SUCCESS_COUNT=0

# Filter out bogus/reserved IPs
filter_valid_ips() {
    grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | while read -r ip; do
        # Skip reserved/documentation ranges
        case "$ip" in
            0.*)         continue ;;  # 0.0.0.0/8 - local
            10.*)        continue ;;  # 10.0.0.0/8 - private
            127.*)       continue ;;  # 127.0.0.0/8 - loopback
            169.254.*)   continue ;;  # 169.254.0.0/16 - link-local
            172.1[6-9].* | 172.2[0-9].* | 172.3[0-1].*) continue ;;  # 172.16.0.0/12 - private
            192.0.2.*)   continue ;;  # 192.0.2.0/24 - TEST-NET-1
            192.168.*)   continue ;;  # 192.168.0.0/16 - private
            198.51.100.*) continue ;; # 198.51.100.0/24 - TEST-NET-2
            203.0.113.*) continue ;;  # 203.0.113.0/24 - TEST-NET-3
            224.*)       continue ;;  # 224.0.0.0/4 - multicast
            240.*)       continue ;;  # 240.0.0.0/4 - reserved
            255.*)       continue ;;  # broadcast
            *)           echo "$ip" ;;
        esac
    done
}

# Try multiple DNS resolution methods
resolve_domain() {
    local domain="$1"
    local ips=""

    # Method 1: dig
    if command -v dig &>/dev/null; then
        ips=$(dig +short "$domain" A 2>/dev/null | filter_valid_ips | sort -u)
        if [[ -n "$ips" ]]; then
            echo "$ips"
            return 0
        fi
    fi

    # Method 2: getent
    if command -v getent &>/dev/null; then
        ips=$(getent ahosts "$domain" 2>/dev/null | awk '{print $1}' | filter_valid_ips | sort -u)
        if [[ -n "$ips" ]]; then
            echo "$ips"
            return 0
        fi
    fi

    # Method 3: host
    if command -v host &>/dev/null; then
        ips=$(host -t A "$domain" 2>/dev/null | grep "has address" | awk '{print $NF}' | filter_valid_ips | sort -u)
        if [[ -n "$ips" ]]; then
            echo "$ips"
            return 0
        fi
    fi

    # Method 4: nslookup
    if command -v nslookup &>/dev/null; then
        ips=$(nslookup "$domain" 2>/dev/null | awk '/^Address: / {print $2}' | filter_valid_ips | sort -u)
        if [[ -n "$ips" ]]; then
            echo "$ips"
            return 0
        fi
    fi

    return 1
}

echo "=== Syncing Claude Chroot IP Allowlist ==="
echo "Output: $IP_FILE"
echo ""

# Domains needed for Claude to function
DOMAINS=(
    # Anthropic API
    "api.anthropic.com"

    # Auth (for Max subscription OAuth)
    "console.anthropic.com"
    "platform.claude.com"
    "claude.ai"

    # Telemetry/metrics (Claude Code reports errors here)
    "statsig.anthropic.com"
    "statsig.com"
    "o1137031.ingest.sentry.io"

    # Nix package cache
    "cache.nixos.org"
)

echo "Resolving domains..."
echo ""

# Create temp file
TEMP_FILE=$(mktemp)

# Header
cat > "$TEMP_FILE" << 'EOF'
# Claude Chroot Allowed IPs
# Generated by claude-chroot-sync-ips.sh
# Review changes before applying!
#
# Format: DOMAIN=IP1,IP2,...

EOF

for domain in "${DOMAINS[@]}"; do
    echo -n "  $domain: "

    # Resolve IPv4 using fallback methods
    if ips=$(resolve_domain "$domain"); then
        ips_csv=$(echo "$ips" | tr '\n' ',' | sed 's/,$//')
        echo "$ips_csv"
        echo "$domain=$ips_csv" >> "$TEMP_FILE"
        ((SUCCESS_COUNT++))
    else
        echo "(failed to resolve)"
        echo "# $domain=(failed to resolve)" >> "$TEMP_FILE"
        FAILED_DOMAINS+=("$domain")
    fi
done

echo ""
echo "Resolved: $SUCCESS_COUNT/${#DOMAINS[@]} domains"

if [[ ${#FAILED_DOMAINS[@]} -gt 0 ]]; then
    echo "Failed: ${FAILED_DOMAINS[*]}"
    echo ""
    echo "Note: Some domains may not exist or may be CNAMEs."
    echo "      The chroot will still work if core domains resolved."
fi

echo ""

# Also add Anthropic's official CIDR ranges
cat >> "$TEMP_FILE" << 'EOF'

# Anthropic official CIDR ranges (from docs.anthropic.com)
# These are stable and won't change without notice
ANTHROPIC_IPV4_INBOUND=160.79.104.0/23
ANTHROPIC_IPV4_OUTBOUND=160.79.104.0/21
ANTHROPIC_IPV6=2607:6bc0::/48
EOF

echo "=== Generated IP List ==="
echo ""
cat "$TEMP_FILE"
echo ""

# Check for changes
if [[ -f "$IP_FILE" ]]; then
    if diff -q "$IP_FILE" "$TEMP_FILE" > /dev/null 2>&1; then
        echo "No changes detected."
        rm "$TEMP_FILE"
        exit 0
    else
        echo "=== Changes detected ==="
        diff "$IP_FILE" "$TEMP_FILE" || true
        echo ""
        read -p "Apply changes? [y/N] " -n 1 -r
        echo ""
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            mv "$TEMP_FILE" "$IP_FILE"
            echo "Updated $IP_FILE"
        else
            rm "$TEMP_FILE"
            echo "Cancelled."
            exit 0
        fi
    fi
else
    echo "Creating new IP file..."
    mkdir -p "$(dirname "$IP_FILE")"
    mv "$TEMP_FILE" "$IP_FILE"
    echo "Created $IP_FILE"
fi

echo ""
echo "Done. Re-enter the chroot to apply new rules."
